/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.dadapush.client.models


import com.squareup.moshi.Json
/**
 * 
 * @param name action button name
 * @param type fix value: link
 * @param url action url
 */
data class Action (
    /* action button name */
    @Json(name = "name")
    val name: kotlin.String,
    /* fix value: link */
    @Json(name = "type")
    val type: Action.Type,
    /* action url */
    @Json(name = "url")
    val url: kotlin.String
) {

    /**
    * fix value: link
    * Values: link
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "link")
        link("link");
    
    }

}

