/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.dadapush.client.models

import com.dadapush.client.models.Action

import com.squareup.moshi.Json
/**
 * 
 * @param actions action size range is 0,3
 * @param content message content
 * @param needPush when value is false, will not send client push
 * @param title message title
 */
data class MessagePushRequest (
    /* message content */
    @Json(name = "content")
    val content: kotlin.String,
    /* when value is false, will not send client push */
    @Json(name = "needPush")
    val needPush: kotlin.Boolean,
    /* message title */
    @Json(name = "title")
    val title: kotlin.String,
    /* action size range is 0,3 */
    @Json(name = "actions")
    val actions: kotlin.Array<Action>? = null
) {

}

