/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.dadapush.client.models

import com.dadapush.client.models.Action

import com.squareup.moshi.Json
/**
 * 
 * @param actions action size range is 0,3
 * @param channelName 
 * @param content 
 * @param createdAt 
 * @param id 
 * @param title 
 */
data class MessageObject (
    @Json(name = "channelName")
    val channelName: kotlin.String,
    @Json(name = "content")
    val content: kotlin.String,
    @Json(name = "createdAt")
    val createdAt: kotlin.String,
    @Json(name = "id")
    val id: kotlin.Long,
    @Json(name = "title")
    val title: kotlin.String,
    /* action size range is 0,3 */
    @Json(name = "actions")
    val actions: kotlin.Array<Action>? = null
) {

}

