/**
* DaDaPush Public API
* DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
*
* The version of the OpenAPI document: v1
* Contact: contacts@dadapush.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.dadapush.client.models

import com.dadapush.client.models.MessageObject

import com.squareup.moshi.Json
/**
 * 
 * @param content 
 * @param totalElements 
 * @param totalPages 
 */
data class PageResponseOfMessageObject (
    @Json(name = "content")
    val content: kotlin.Array<MessageObject>? = null,
    @Json(name = "totalElements")
    val totalElements: kotlin.Long? = null,
    @Json(name = "totalPages")
    val totalPages: kotlin.Long? = null
) {

}

